### ISSUE TITLE
studyhelper2.7.0-2一到分享就闪退了

### ISSUE THREAD

**Issue by snowxiaying** [studyhelperhelper/studyhelper#101]

**Comment by snowxiaying** [comment]
12-12 05:28:21.371  8473  8540 D 延时了几秒: 1
12-12 05:28:22.255  8473  8540 E AndroidRuntime: FATAL EXCEPTION: Thread-3
12-12 05:28:22.255  8473  8540 E AndroidRuntime: Process: com.study.helper, PID: 8473
12-12 05:28:22.255  8473  8540 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
12-12 05:28:22.255  8473  8540 E AndroidRuntime: 	at com.study.helper.job.StudyHelperJob.shareNum(StudyHelperJob.java:853)
12-12 05:28:22.255  8473  8540 E AndroidRuntime: 	at com.study.helper.job.StudyHelperJob$1.run(StudyHelperJob.java:325)
